-- All Products
SELECT *
FROM PRODUCTS;

-- High Price of Products
SELECT PRODUCT_NAME, CATEGORY
FROM PRODUCTS
WHERE PRICE > 100.00;

-- Average Salary
SELECT AVG(SALARY) AS AVG_SALARY
FROM WORKS;

--Locate People
-- LIKE STATEMENT IS CASE SENSITIVE BASED ON THE DATABASE
-- MYSQL IS NOT CASE SENSITIVE, WHILE POSTGRES IS.
-- FOR POSTGRES - USE ILIKE INSTEAD OF LIKE.
-- FOR ORACLE USE LOWER(LOCATION) LIKE LOWER('s%');
SELECT DEPARTMENT_NAME, LOCATION 
FROM DEPARTMENTS 
WHERE LOCATION LIKE 'S%';

-- Distinct Companies
SELECT DISTINCT COMPANY_NAME 
FROM WORKS;

-- Fiction Collection Size
SELECT COUNT(*) AS FICTION_COUNT
FROM BOOKS
WHERE UPPER(GENRE) = 'FICTION';

-- List of Movies with Ratings
SELECT MOVIE_NAME 
FROM CINEMA
WHERE RATING IS NOT NULL AND
RATING BETWEEN 7 AND 8.9;

-- Handling NULL Values
SELECT BOOK_ID, TITLE, AUTHOR, PUBLISHED_YEAR
FROM LIBRARY
WHERE RATING IS NULL;

-- Salary of Employees
SELECT EMPLOYEE_NAME, COMPANY, SALARY
FROM EMPLOYEES
WHERE CATEGORY IS NOT NULL AND 
LOWER(CATEGORY) = 'full-time'
ORDER BY SALARY DESC;

-- Department of Each Employee
SELECT DEPARTMENT, COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEES
WHERE DEPARTMENT IS NOT NULL
GROUP BY DEPARTMENT;

-- Article views
SELECT DISTINCT AUTHOR_ID, AUTHOR_NAME, PUBLICATION_NAME 
FROM VIEWS
WHERE VIEW_COUNT = 0
ORDER BY AUTHOR_ID ASC;

-- Player Performance Insights
SELECT DISTINCT P.PLAYER_NAME, P.SCORE
FROM PLAYERS AS P 
INNER JOIN MATCHES AS M ON 
    M.WINNER = P.PLAYER_NAME
ORDER BY SCORE DESC
LIMIT 3;

-- Player Details
SELECT M.MATCH_ID,
       M.PLAYER_1,
       M.PLAYER_2,
       M.WINNER,
       M.MATCH_DATE,
       P.SCORE
FROM MATCHES M
INNER JOIN PLAYERS P
  ON M.WINNER = P.PLAYER_NAME
ORDER BY M.MATCH_DATE DESC
LIMIT 5;
