--175 Combine 2 tables 
SELECT PRSN.FIRSTNAME, PRSN.LASTNAME, ADDR.CITY, ADDR.STATE
FROM PERSON AS PRSN
LEFT JOIN ADDRESS AS ADDR ON 
    ADDR.PERSONID = PRSN.PERSONID;

--181 Employees earning more than their manager
SELECT EMP.NAME AS Employee
FROM EMPLOYEE AS EMP
JOIN EMPLOYEE AS MGR ON 
    MGR.ID = EMP.MANAGERID
WHERE EMP.SALARY > MGR.SALARY;

--182 Duplicate Emails
SELECT PRSN.EMAIL
FROM PERSON AS PRSN
GROUP BY EMAIL 
HAVING COUNT(*) > 1;

--183 Customers who never order

--196 Delete Duplicate Emails

--197 Rising Temperature
SELECT TODAY.ID 
FROM WEATHER AS TODAY
JOIN WEATHER AS YESTERDAY ON 
    TODAY.RECORDDATE = DATE_ADD(YESTERDAY.RECORDDATE, INTERVAL 1 DAY) AND 
    TODAY.TEMPERATURE > YESTERDAY.TEMPERATURE;
