--https://leetcode.com/studyplan/top-sql-50/
-- 1757. Recyclable and Low Fat Products
SELECT PRODUCT_ID
FROM PRODUCTS
WHERE LOW_FATS = 'Y' AND 
      RECYCLABLE = 'Y'; 

-- 584. Find Customer Referee
SELECT NAME
FROM CUSTOMER
WHERE REFEREE_ID != 2 OR REFEREE_ID IS NULL;

-- 595. Big Countries
SELECT NAME, POPULATION, AREA
FROM WORLD 
WHERE AREA >= 3000000 OR
      POPULATION >= 25000000  

-- 1148. Article Views I
SELECT DISTINCT AUTHOR_ID AS ID
FROM VIEWS 
WHERE AUTHOR_ID = VIEWER_ID
ORDER BY AUTHOR_ID ASC;

-- 1683. Invalid Tweets
SELECT TWEET_ID
FROM TWEETS
WHERE LENGTH(CONTENT) > 15;

-- 1378. Replace Employee ID With The Unique Identifier
SELECT UNI.UNIQUE_ID, EMP.NAME 
FROM EMPLOYEES AS EMP
LEFT JOIN EMPLOYEEUNI AS UNI ON UNI.ID = EMP.ID;

-- 1068. Product Sales Analysis I
SELECT PRD.PRODUCT_NAME, SALE.YEAR, SALE.PRICE
FROM SALES AS SALE
JOIN PRODUCT AS PRD ON PRD.PRODUCT_ID = SALE.PRODUCT_ID

-- 1581. Customer Who Visited but Did Not Make Any Transactions
SELECT VISIT.CUSTOMER_ID, COUNT(VISIT.VISIT_ID) AS COUNT_NO_TRANS
FROM VISITS AS VISIT
LEFT JOIN TRANSACTIONS AS TRANS ON TRANS.VISIT_ID = VISIT.VISIT_ID
WHERE TRANS.TRANSACTION_ID IS NULL
GROUP BY CUSTOMER_ID;

-- 197. Rising Temperature
SELECT w1.id
FROM Weather w1, Weather w2
WHERE DATEDIFF(w1.recordDate, w2.recordDate) = 1 AND w1.temperature > w2.temperature;

-- 1661. Average Time of Process per Machine

-- 577. Employee Bonus
select e.name , b.bonus
from employee as e 
left outer join bonus as b on e.empid = b.empid
where b.bonus < 1000 or b.bonus is null;

-- 1280. Students and Examinations
SELECT STUD.STUDENT_ID,
       STUD.STUDENT_NAME,
       SUB.SUBJECT_NAME,
       COUNT(EXAM.SUBJECT_NAME) AS ATTENDED_EXAMS
FROM STUDENTS AS STUD
CROSS JOIN SUBJECTS AS SUB
LEFT JOIN EXAMINATIONS AS EXAM ON EXAM.STUDENT_ID = STUD.STUDENT_ID AND 
                                  EXAM.SUBJECT_NAME = SUB.SUBJECT_NAME
GROUP BY STUD.STUDENT_ID, STUD.STUDENT_NAME, SUB.SUBJECT_NAME
ORDER BY STUD.STUDENT_ID, SUB.SUBJECT_NAME;   
      
-- 570. MANAGERS WITH ATLEAST 5 DIRECT REPORTS
SELECT NAME
FROM EMPLOYEE
JOIN (SELECT MANAGERID
      FROM EMPLOYEE
      GROUP BY MANAGERID
      HAVING COUNT(*) >= 5
) M
WHERE EMPLOYEE.ID = M.MANAGERID 

--OR 
SELECT EMP.NAME
FROM EMPLOYEE AS EMP
JOIN EMPLOYEE AS MNG ON MNG.MANAGERID = EMP.ID
GROUP BY EMP.ID, EMP.NAME
HAVING COUNT(*) >= 5;

-- 1934. Confirmation Rate

-- 620. Not Boring Movies
SELECT *
FROM CINEMA
WHERE DESCRIPTION <> "boring" AND 
      ID % 2 <> 0  
 ORDER BY RATING DESC    

-- 1251. Average Selling Price

-- 1075. Project Employees I
SELECT PROJECT_ID, ROUND(AVG(EXPERIENCE_YEARS), 2) AS AVERAGE_YEARS
FROM PROJECT AS PROJ
JOIN EMPLOYEE AS EMP ON EMP.EMPLOYEE_ID = PROJ.EMPLOYEE_ID
GROUP BY PROJECT_ID 

-- 1633. Percentage of Users Attended a Contest

-- 1193. Monthly Transactions I


-- 1211. Queries Quality and Percentage
