--https://leetcode.com/studyplan/top-sql-50/

--570. MANAGERS WITH ATLEAST 5 DIRECT REPORTS
SELECT NAME
FROM EMPLOYEE
JOIN (SELECT MANAGERID
      FROM EMPLOYEE
      GROUP BY MANAGERID
      HAVING COUNT(*) >= 5
) M
WHERE EMPLOYEE.ID = M.MANAGERID 

--OR 
SELECT EMP.NAME
FROM EMPLOYEE AS EMP
JOIN EMPLOYEE AS MNG ON MNG.MANAGERID = EMP.ID
GROUP BY EMP.ID, EMP.NAME
HAVING COUNT(*) >= 5;
